doctrine:
    dbal:
        default_connection: systemeio
        connections:
            systemeio:
                use_savepoints: true
                driver: 'pdo_pgsql'
                server_version: '13'
                charset: utf8
                host: '%env(DB_HOST)%'
                dbname: '%env(DB_DBNAME)%'
                user: '%env(DB_USER)%'
                password: '%env(DB_PASSWORD)%'
                port: '%env(DB_PORT)%'


    orm:
        default_entity_manager: default
        entity_managers:
            default:
                report_fields_where_declared: true
                connection: systemeio
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    AppDomain:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Domain'
                        prefix: 'App\Domain'
                        alias: Domain

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
