
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:


imports:
    - { resource: 'services/application.yaml' }
    - { resource: 'services/presentation.yaml' }
    - { resource: 'services/repositories.yaml' }
    - { resource: 'services/usecases.yaml' }



    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
